const EventEmitter = require('events');
const qrcode = require('qrcode');
const client = require('../config/whatsapp');

/**
 * Service to manage the WhatsApp Web client state and event handlers.
 * Extends EventEmitter so other components (like SocketService) can register
 * reactive listeners without creating circular dependencies.
 */
class WhatsappService extends EventEmitter {
    constructor() {
        super();
        this.status = 'DISCONNECTED'; // DISCONNECTED, INITIALIZING, QR_READY, CONNECTED
        this.qrCodeData = null; // Stores the current base64 QR code image
        this.setupEventHandlers();
    }

    setupEventHandlers() {
        // Triggered when a login QR code is generated by whatsapp-web.js
        client.on('qr', async (qr) => {
            try {
                this.status = 'QR_READY';
                // Convert the raw QR text into a base64 Data URL (png) for easy rendering in <img> tags
                const qrImage = await qrcode.toDataURL(qr);
                this.qrCodeData = qrImage;
                this.emit('qr', qrImage);
                this.emit('status', this.status);
                console.log('WhatsApp QR Code generated and converted to Data URL.');
            } catch (err) {
                console.error('Error generating QR code Data URL:', err);
            }
        });

        // Triggered when successfully logged in and the client is ready to interact
        client.on('ready', () => {
            this.status = 'CONNECTED';
            this.qrCodeData = null;
            this.emit('ready');
            this.emit('status', this.status);
            console.log('WhatsApp client is ready and connected!');
        });

        client.on('authenticated', () => {
            console.log('WhatsApp client authenticated successfully.');
        });

        client.on('auth_failure', (msg) => {
            this.status = 'DISCONNECTED';
            this.qrCodeData = null;
            this.emit('auth_failure', msg);
            this.emit('status', this.status);
            console.error('WhatsApp authentication failed:', msg);
        });

        // Triggered when the client is logged out or loses connection
        client.on('disconnected', (reason) => {
            this.status = 'DISCONNECTED';
            this.qrCodeData = null;
            this.emit('disconnected', reason);
            this.emit('status', this.status);
            console.log('WhatsApp client was disconnected. Reason:', reason);

            // Re-initialize to generate a new QR code automatically
            this.initialize();
        });

        // Listen for incoming messages to emit them to the UI console for demo purposes
        client.on('message', (message) => {
            this.emit('message_received', {
                from: message.from,
                body: message.body,
                timestamp: message.timestamp
            });
        });
    }

    /**
     * Launch/Initialize the WhatsApp Web headless browser.
     */
    initialize() {
        if (this.status === 'INITIALIZING' || this.status === 'CONNECTED') {
            console.log(`WhatsApp client initialization skipped. Current status: ${this.status}`);
            return;
        }

        this.status = 'INITIALIZING';
        this.emit('status', this.status);
        console.log('Initializing WhatsApp client (Puppeteer)...');

        client.initialize().catch((err) => {
            console.error('Failed to initialize WhatsApp client:', err);
            this.status = 'DISCONNECTED';
            this.emit('status', this.status);
        });
    }

    getStatus() {
        return this.status;
    }

    getQrCode() {
        return this.qrCodeData;
    }

    /**
     * Formats the destination number and sends a text message.
     * @param {string} number - The recipient's phone number (with country/area codes)
     * @param {string} message - The message payload
     */
    async sendMessage(number, message) {
        if (this.status !== 'CONNECTED') {
            throw new Error('WhatsApp client is not connected. Authenticate first.');
        }

        // Clean the number: remove spaces, dashes, parenthesis, plus sign
        let formattedNumber = number.replace(/\D/g, '');

        // Format to WhatsApp format (e.g., 5511999999999@c.us)
        if (!formattedNumber.endsWith('@c.us')) {
            formattedNumber = `${formattedNumber}@c.us`;
        }

        const response = await client.sendMessage(formattedNumber, message);
        return {
            id: response.id.id,
            to: response.to,
            body: response.body,
            timestamp: response.timestamp
        };
    }
}

// Export as a singleton service
module.exports = new WhatsappService();
