/**
 * WhatsappService Unit Tests
 */

// Mock the whatsapp-web.js module BEFORE requiring our service.
// This prevents Jest from trying to launch Puppeteer during unit testing.
jest.mock('whatsapp-web.js', () => {
    const EventEmitter = require('events');

    class MockLocalAuth {
        constructor(options) {
            this.options = options;
        }
    }

    class MockClient extends EventEmitter {
        constructor(options) {
            super();
            this.options = options;
        }
        initialize() {
            return Promise.resolve();
        }
        sendMessage(number, message) {
            return Promise.resolve({
                id: { id: 'mock_msg_id_98765' },
                to: number,
                body: message,
                timestamp: 1690000000
            });
        }
    }

    return {
        Client: MockClient,
        LocalAuth: MockLocalAuth
    };
});

const whatsappService = require('../src/services/whatsappService');
const clientInstance = require('../src/config/whatsapp');

describe('WhatsappService Unit Tests', () => {
    beforeEach(() => {
        jest.clearAllMocks();
        // Reset singleton status
        whatsappService.status = 'DISCONNECTED';
        whatsappService.qrCodeData = null;
    });

    test('should transition status to INITIALIZING on initialize', () => {
        whatsappService.initialize();
        expect(whatsappService.getStatus()).toBe('INITIALIZING');
    });

    test('should transition status to CONNECTED when client fires ready', () => {
        clientInstance.emit('ready');
        expect(whatsappService.getStatus()).toBe('CONNECTED');
    });

    test('should convert QR codes into events', (done) => {
        whatsappService.once('qr', (qrBase64) => {
            // qr base64 image generated by node-qrcode begins with data:image/png;base64,
            expect(qrBase64).toContain('data:image/png;base64,');
            expect(whatsappService.getStatus()).toBe('QR_READY');
            done();
        });

        // Fire fake QR code text string
        clientInstance.emit('qr', 'mock_whatsapp_qr_text_string_data');
    });

    test('should format and sanitize target phone numbers correctly', async () => {
        whatsappService.status = 'CONNECTED';
        const spySendMessage = jest.spyOn(clientInstance, 'sendMessage');

        // Input with international country code, spaces, parentheses, dashes
        const rawNumber = '+55 (11) 99999-9999';
        const payload = 'Test text payload';

        const response = await whatsappService.sendMessage(rawNumber, payload);

        // Sanity Check: All formatting symbols stripped, '@c.us' appended
        expect(spySendMessage).toHaveBeenCalledWith('5511999999999@c.us', payload);
        expect(response.to).toBe('5511999999999@c.us');
        expect(response.id).toBe('mock_msg_id_98765');
    });

    test('should throw error if attempting to send message while disconnected', async () => {
        whatsappService.status = 'DISCONNECTED';

        await expect(
            whatsappService.sendMessage('5511999999999', 'Failure message')
        ).rejects.toThrow('WhatsApp client is not connected');
    });
});
